"""
app.py — Sakshi OCR: Streamlit front-end for the IGNOU Assignment Q&A pipeline.

Run with:
    streamlit run app.py

Requires environment variables:
    ANTHROPIC_API_KEY
    DATALAB_API_KEY
"""

import os
import io
import json
import traceback

import streamlit as st

import pipeline

st.set_page_config(page_title="Sakshi OCR — IGNOU Q&A Extractor", layout="wide")

st.title("📝 Sakshi OCR — IGNOU Assignment Q&A Extractor")
st.caption(
    "OCR → question extraction → strict line-range answer mapping → "
    "self-correction loop → rescue passes. Answer text is always sliced "
    "directly from raw OCR output — never generated by the LLM."
)

# ---------------------------------------------------------------------------
# Sidebar: config / status
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("Status")
    anthropic_ok = bool(os.environ.get("ANTHROPIC_API_KEY"))
    datalab_ok = bool(os.environ.get("DATALAB_API_KEY"))
    st.write(("✅" if anthropic_ok else "❌") + " ANTHROPIC_API_KEY")
    st.write(("✅" if datalab_ok else "❌") + " DATALAB_API_KEY")
    if not (anthropic_ok and datalab_ok):
        st.warning("Set both API keys as environment variables before running.")

    st.divider()
    st.header("Pipeline settings")
    st.caption(f"Model: `{pipeline.CLAUDE_MODEL}`")
    st.caption(f"Max chars/chunk: {pipeline.MAX_CHARS_PER_CHUNK}")
    st.caption(f"Min lines between starts: {pipeline.MIN_LINES_BETWEEN_STARTS}")
    st.caption(f"Max refinement passes: {pipeline.MAX_REFINEMENT_PASSES}")

# ---------------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------------
if "result" not in st.session_state:
    st.session_state.result = None
if "error" not in st.session_state:
    st.session_state.error = None

# ---------------------------------------------------------------------------
# Upload + run
# ---------------------------------------------------------------------------
uploaded = st.file_uploader("Upload a scanned IGNOU assignment PDF", type=["pdf"])

col_run, col_clear = st.columns([1, 1])
run_clicked = col_run.button("Run pipeline", type="primary", disabled=uploaded is None)
if col_clear.button("Clear results"):
    st.session_state.result = None
    st.session_state.error = None

if run_clicked and uploaded is not None:
    tmp_path = os.path.join("/tmp", uploaded.name)
    with open(tmp_path, "wb") as f:
        f.write(uploaded.getbuffer())

    st.session_state.error = None
    with st.spinner("Running full pipeline — this can take a few minutes for long assignments..."):
        try:
            st.session_state.result = pipeline.run_full_pipeline(tmp_path)
        except Exception as e:
            st.session_state.error = f"{e}\n\n{traceback.format_exc()}"
            st.session_state.result = None

# ---------------------------------------------------------------------------
# Error display
# ---------------------------------------------------------------------------
if st.session_state.error:
    st.error("Pipeline failed.")
    with st.expander("Show traceback"):
        st.code(st.session_state.error)

# ---------------------------------------------------------------------------
# Results display
# ---------------------------------------------------------------------------
result = st.session_state.result
if result is not None:
    n_pairs = len(result.qa_pairs)
    n_answered = sum(1 for p in result.qa_pairs if p.a_start_line is not None)
    n_unmatched = len(result.unmatched_answers)
    n_warnings = len(result.warnings)

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Questions found", n_pairs)
    m2.metric("Answered", n_answered)
    m3.metric("Unmatched answer blocks", n_unmatched)
    m4.metric("Warnings", n_warnings)

    if result.warnings:
        with st.expander(f"⚠️ {n_warnings} warning(s)", expanded=False):
            for w in result.warnings:
                st.write("- " + w)

    tab_qa, tab_unmatched, tab_raw, tab_export = st.tabs(
        ["Q&A pairs", "Unmatched answers", "Raw OCR (numbered)", "Export"]
    )

    with tab_qa:
        for i, p in enumerate(result.qa_pairs, start=1):
            badge = {"llm": "🟢", "rescue": "🟡", "final_guarantee": "🔴"}.get(p.source, "")
            with st.expander(
                f"{badge} Q{i} — lines {p.q_start_line}-{p.q_end_line} "
                f"→ answer lines {p.a_start_line}-{p.a_end_line}"
                if p.a_start_line else
                f"{badge} Q{i} — lines {p.q_start_line}-{p.q_end_line} → NO ANSWER FOUND"
            ):
                st.markdown("**Question:**")
                st.write(p.question_text or "*(not extracted)*")
                st.markdown("**Answer (raw OCR, unedited):**")
                if p.answer_text:
                    st.text(p.answer_text)
                else:
                    st.info("No answer mapped for this question.")
                st.caption(f"source: {p.source} · continues: {p.continues}")

    with tab_unmatched:
        if not result.unmatched_answers:
            st.success("No unmatched answer blocks.")
        else:
            for i, u in enumerate(result.unmatched_answers, start=1):
                with st.expander(f"Unmatched block {i} — lines {u.start_line}-{u.end_line}"):
                    st.text(u.text)

    with tab_raw:
        raw_text = "\n".join(
            f"{n}: {t}" for n, t in sorted(result.raw_lines.items())
        )
        st.text_area("Numbered raw OCR text", raw_text, height=500)

    with tab_export:
        export_json = {
            "qa_pairs": [
                {
                    "question": p.question_text,
                    "answer": p.answer_text,
                    "q_start_line": p.q_start_line,
                    "q_end_line": p.q_end_line,
                    "a_start_line": p.a_start_line,
                    "a_end_line": p.a_end_line,
                    "source": p.source,
                }
                for p in result.qa_pairs
            ],
            "unmatched_answers": [
                {"start_line": u.start_line, "end_line": u.end_line, "text": u.text}
                for u in result.unmatched_answers
            ],
            "warnings": result.warnings,
        }
        json_bytes = json.dumps(export_json, ensure_ascii=False, indent=2).encode("utf-8")
        st.download_button(
            "Download JSON",
            data=json_bytes,
            file_name="qa_extraction.json",
            mime="application/json",
        )

        # Plain-text export: Q/A pairs only, human-readable
        txt_lines = []
        for i, p in enumerate(result.qa_pairs, start=1):
            txt_lines.append(f"Q{i}: {p.question_text}")
            txt_lines.append(f"A{i}: {p.answer_text if p.answer_text else '[NO ANSWER FOUND]'}")
            txt_lines.append("")
        txt_bytes = "\n".join(txt_lines).encode("utf-8")
        st.download_button(
            "Download plain text",
            data=txt_bytes,
            file_name="qa_extraction.txt",
            mime="text/plain",
        )
else:
    st.info("Upload a PDF and click **Run pipeline** to get started.")
