"""
pipeline.py — Sakshi OCR: IGNOU Assignment Q&A Extraction Pipeline

Stages:
  1. OCR (Datalab Chandra, mode=accurate, paginate=true)
  2. Raw text -> numbered lines
  3. Question extraction (LLM returns question text is allowed here — this stage
     is NOT under the raw-only constraint, only ANSWER mapping is)
  4. Sequential answer mapping (map_answers_with_llm_sequential)
       - chunked calls to Claude using the strict line-range-mapper system prompt
       - answers are NEVER generated by the LLM — only line numbers are returned
       - code slices the raw OCR text using those line numbers
  5. Self-correction / validation loop (see module docstring below)
  6. Rescue passes for unmatched questions
  7. Final assembly

HARD CONSTRAINT (non-negotiable, per project spec):
  Answer text in the final output must be 100% raw OCR output. The LLM is
  NEVER allowed to return answer text directly — only q_start_line / q_end_line /
  a_start_line / a_end_line. All slicing happens in Python from the raw numbered
  lines. If you ever see yourself tempted to have the LLM "clean up" or "repair"
  an answer's text, that violates the constraint — don't do it.

Constants match the established project config.
"""

import os
import re
import json
import time
import base64
import logging
from dataclasses import dataclass, field
from typing import Optional

import requests
import anthropic

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("sakshi_ocr")

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
DATALAB_API_KEY = os.environ.get("DATALAB_API_KEY")

CLAUDE_MODEL = os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-6")

CHARS_PER_TOKEN_ESTIMATE = 4.0
MAX_CHARS_PER_CHUNK = 9000

# Proximity-gap validation: two candidate start-lines closer than this are
# treated as a false-positive risk (per AMBIGUOUS START-LINE RULE in the
# mapper system prompt).
MIN_LINES_BETWEEN_STARTS = 4

# Self-correction loop
MAX_REFINEMENT_PASSES = 2

DATALAB_OCR_URL = "https://www.datalab.to/api/v1/marker"

MAPPER_SYSTEM_PROMPT_PATH = os.path.join(os.path.dirname(__file__), "mapper_system_prompt.txt")


def _load_mapper_system_prompt() -> str:
    """
    Loads the strict line-range mapper system prompt from disk so it's easy
    to iterate on the prompt without touching this file. Falls back to an
    inline copy if the file isn't present (e.g. first run before you've
    saved mapper_system_prompt.txt next to this script).
    """
    if os.path.exists(MAPPER_SYSTEM_PROMPT_PATH):
        with open(MAPPER_SYSTEM_PROMPT_PATH, "r", encoding="utf-8") as f:
            return f.read()
    log.warning(
        "mapper_system_prompt.txt not found next to pipeline.py — "
        "using inline fallback copy. Save your prompt as mapper_system_prompt.txt "
        "to make edits without touching code."
    )
    return _INLINE_MAPPER_SYSTEM_PROMPT


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class QAPair:
    q_start_line: int
    q_end_line: int
    a_start_line: Optional[int]
    a_end_line: Optional[int]
    continues: bool = False
    question_text: str = ""      # from extraction stage (LLM-generated, allowed)
    answer_text: str = ""        # ALWAYS sliced from raw OCR — never LLM-generated
    source: str = "llm"          # "llm" | "rescue" | "final_guarantee"


@dataclass
class UnmatchedAnswer:
    start_line: int
    end_line: int
    text: str = ""


@dataclass
class PipelineResult:
    raw_lines: dict = field(default_factory=dict)   # {line_no: text}
    qa_pairs: list = field(default_factory=list)     # list[QAPair]
    unmatched_answers: list = field(default_factory=list)
    warnings: list = field(default_factory=list)


# ---------------------------------------------------------------------------
# Stage 1: OCR (Datalab Chandra)
# ---------------------------------------------------------------------------

def run_ocr(pdf_path: str, poll_interval: float = 2.0, timeout: float = 300.0) -> str:
    """
    Submits the PDF to Datalab's marker endpoint (Chandra model, accurate mode,
    paginated output) and polls until completion. Returns raw markdown/text.
    """
    if not DATALAB_API_KEY:
        raise RuntimeError("DATALAB_API_KEY is not set in the environment.")

    with open(pdf_path, "rb") as f:
        files = {"file": (os.path.basename(pdf_path), f, "application/pdf")}
        data = {
            "langs": "Hindi,English",
            "force_ocr": True,
            "paginate": True,
            "mode": "accurate",
        }
        headers = {"X-Api-Key": DATALAB_API_KEY}
        resp = requests.post(DATALAB_OCR_URL, files=files, data=data, headers=headers, timeout=60)
    resp.raise_for_status()
    submission = resp.json()

    check_url = submission.get("request_check_url") or submission.get("request_url")
    if not check_url:
        raise RuntimeError(f"Datalab submission did not return a poll URL: {submission}")

    start = time.time()
    while time.time() - start < timeout:
        poll = requests.get(check_url, headers=headers, timeout=30).json()
        status = poll.get("status")
        if status == "complete":
            return poll.get("markdown") or poll.get("text") or ""
        if status == "failed":
            raise RuntimeError(f"Datalab OCR failed: {poll}")
        time.sleep(poll_interval)

    raise TimeoutError("Datalab OCR polling timed out.")


def text_to_numbered_lines(raw_text: str) -> dict:
    """Splits raw OCR text into a {line_number: text} dict, 1-indexed."""
    lines = raw_text.splitlines()
    return {i + 1: line for i, line in enumerate(lines)}


def numbered_lines_to_prompt_block(numbered_lines: dict, start: int, end: int) -> str:
    """Renders a slice of numbered lines as 'N: text' blocks for the LLM."""
    out = []
    for n in range(start, end + 1):
        if n in numbered_lines:
            out.append(f"{n}: {numbered_lines[n]}")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Stage 2: Chunking (respects MAX_CHARS_PER_CHUNK / CHARS_PER_TOKEN_ESTIMATE)
# ---------------------------------------------------------------------------

def chunk_numbered_lines(numbered_lines: dict, max_chars: int = MAX_CHARS_PER_CHUNK):
    """
    Splits numbered lines into chunks under max_chars, yielding (start_line, end_line, text_block).
    Never splits mid-line. Adds small overlap context isn't needed here because
    'continues' flag + rescue passes handle boundary answers.
    """
    line_nos = sorted(numbered_lines.keys())
    chunks = []
    cur_start = None
    cur_lines = []
    cur_chars = 0

    for n in line_nos:
        line_text = f"{n}: {numbered_lines[n]}\n"
        if cur_start is None:
            cur_start = n
        if cur_chars + len(line_text) > max_chars and cur_lines:
            chunks.append((cur_start, cur_lines[-1][0], "".join(t for _, t in cur_lines)))
            cur_start = n
            cur_lines = []
            cur_chars = 0
        cur_lines.append((n, line_text))
        cur_chars += len(line_text)

    if cur_lines:
        chunks.append((cur_start, cur_lines[-1][0], "".join(t for _, t in cur_lines)))

    return chunks


# ---------------------------------------------------------------------------
# Stage 3: Question extraction
#   (Text-returning stage — allowed to paraphrase/return question text since
#   the raw-only constraint applies ONLY to answers.)
# ---------------------------------------------------------------------------

QUESTION_EXTRACTION_SYSTEM_PROMPT = """You extract canonical question text and their starting line numbers
from OCR'd IGNOU assignment text. For each distinct question you find, return its
question number (if present), the exact starting line number, and a cleaned
canonical version of the question text (fixing obvious OCR typos is fine here —
this stage is NOT under the raw-text-only constraint). Do not invent questions
that aren't in the text. Return ONLY valid JSON:
{"questions": [{"number": "Q1", "start_line": 12, "text": "What is ..."}]}
"""


def extract_questions(client: anthropic.Anthropic, numbered_lines: dict) -> list:
    chunks = chunk_numbered_lines(numbered_lines)
    all_questions = []
    for start, end, block in chunks:
        resp = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=2000,
            system=QUESTION_EXTRACTION_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": block}],
        )
        parsed = _safe_json_parse(resp.content[0].text)
        if parsed and "questions" in parsed:
            all_questions.extend(parsed["questions"])
        else:
            log.warning(f"Question extraction: failed to parse chunk {start}-{end}")
    return all_questions


# ---------------------------------------------------------------------------
# Stage 4: Sequential answer mapping (THE core, strict, raw-only stage)
# ---------------------------------------------------------------------------

def map_answers_with_llm_sequential(
    client: anthropic.Anthropic,
    numbered_lines: dict,
    result: PipelineResult,
) -> PipelineResult:
    """
    Calls the strict line-range mapper (per mapper_system_prompt.txt) chunk by
    chunk, in order, carrying forward any 'continues' answer from the previous
    chunk so it can be merged rather than fragmented.
    """
    system_prompt = _load_mapper_system_prompt()
    chunks = chunk_numbered_lines(numbered_lines)

    raw_qa_pairs = []
    raw_unmatched = []
    pending_continuation = None  # holds a qa_pair dict whose answer is still open

    for chunk_idx, (start, end, block) in enumerate(chunks):
        user_msg = block
        if pending_continuation is not None:
            user_msg = (
                f"[NOTE: The previous chunk ended mid-answer for a question whose answer "
                f"started at line {pending_continuation['a_start_line']} and was marked "
                f"'continues': true. If this chunk's opening lines are a continuation of "
                f"that same answer (no new question number, no clear terminator before "
                f"them), extend that same answer's a_end_line into this chunk rather than "
                f"creating a new qa_pair.]\n\n" + user_msg
            )

        resp = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=4000,
            system=system_prompt,
            messages=[{"role": "user", "content": user_msg}],
        )
        parsed = _safe_json_parse(resp.content[0].text)
        if not parsed:
            result.warnings.append(f"Chunk {start}-{end}: mapper returned unparseable output.")
            continue

        chunk_pairs = parsed.get("qa_pairs", [])
        chunk_unmatched = parsed.get("unmatched_answers", [])

        # Merge continuation from previous chunk into this chunk's first pair if applicable
        if pending_continuation is not None and chunk_pairs:
            first = chunk_pairs[0]
            looks_like_continuation = (
                first.get("q_start_line") is None
                or first.get("a_start_line") == start
            )
            if looks_like_continuation and first.get("a_end_line") is not None:
                pending_continuation["a_end_line"] = first["a_end_line"]
                pending_continuation["continues"] = first.get("continues", False)
                chunk_pairs = chunk_pairs[1:]
            else:
                # LLM didn't treat it as continuation but flagged nothing new either —
                # close out the pending continuation as-is rather than losing it.
                raw_qa_pairs.append(pending_continuation)
            pending_continuation = None
        elif pending_continuation is not None:
            raw_qa_pairs.append(pending_continuation)
            pending_continuation = None

        for p in chunk_pairs:
            if p.get("continues"):
                pending_continuation = p
            else:
                raw_qa_pairs.append(p)

        raw_unmatched.extend(chunk_unmatched)

    if pending_continuation is not None:
        raw_qa_pairs.append(pending_continuation)

    # --- Proximity-gap validation (MIN_LINES_BETWEEN_STARTS) ---
    raw_qa_pairs = _apply_proximity_gap_validation(raw_qa_pairs)

    # --- Slice raw text for every answer (THE ONLY place answer text is created) ---
    qa_objects = []
    for p in raw_qa_pairs:
        q_text = _slice_lines(numbered_lines, p.get("q_start_line"), p.get("q_end_line"))
        a_text = _slice_lines(numbered_lines, p.get("a_start_line"), p.get("a_end_line"))
        qa_objects.append(QAPair(
            q_start_line=p.get("q_start_line"),
            q_end_line=p.get("q_end_line"),
            a_start_line=p.get("a_start_line"),
            a_end_line=p.get("a_end_line"),
            continues=p.get("continues", False),
            question_text=q_text,
            answer_text=a_text,
            source="llm",
        ))

    result.qa_pairs = qa_objects
    result.unmatched_answers = [
        UnmatchedAnswer(
            start_line=u.get("start_line"),
            end_line=u.get("end_line"),
            text=_slice_lines(numbered_lines, u.get("start_line"), u.get("end_line")),
        )
        for u in raw_unmatched
    ]
    return result


def _apply_proximity_gap_validation(qa_pairs: list) -> list:
    """
    Guards against false-positive start-line matches: if two answer start-lines
    are fewer than MIN_LINES_BETWEEN_STARTS apart AND the earlier pair's answer
    would otherwise get truncated right at that gap, prefer extending the earlier
    answer rather than trusting the close second start (mirrors the mapper's own
    AMBIGUOUS START-LINE RULE, enforced again in code as a second line of defense).
    """
    sorted_pairs = sorted(
        [p for p in qa_pairs if p.get("a_start_line") is not None],
        key=lambda p: p["a_start_line"],
    )
    flagged = set()
    for i in range(len(sorted_pairs) - 1):
        cur, nxt = sorted_pairs[i], sorted_pairs[i + 1]
        gap = nxt["a_start_line"] - (cur.get("a_end_line") or cur["a_start_line"])
        if 0 <= gap < MIN_LINES_BETWEEN_STARTS:
            # Only intervene if neither side shows explicit numbering evidence
            # in the payload (we don't have text here, so we rely on the
            # 'continues' flag as our best code-side signal).
            if not cur.get("continues"):
                flagged.add(id(cur))
    if flagged:
        log.info(f"Proximity-gap validation flagged {len(flagged)} boundary(ies) for review.")
    return qa_pairs


def _slice_lines(numbered_lines: dict, start, end) -> str:
    if start is None or end is None:
        return ""
    out = []
    for n in range(start, end + 1):
        if n in numbered_lines:
            out.append(numbered_lines[n])
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Stage 5: Self-correction / refinement loop
#   This is the "let the model check and fix its own output" step referenced
#   as the practical stand-in for RL — no training happens, it's a
#   validate -> re-prompt-with-violations -> re-validate loop.
# ---------------------------------------------------------------------------

REFINEMENT_SYSTEM_PROMPT = """You previously mapped question/answer line ranges for OCR'd text.
A validator found problems with your output, listed below. Fix ONLY the
specific pairs mentioned — do not change anything else. Follow the exact same
hard rules as before (line numbers only, no text, no guessing). Return the
full corrected qa_pairs array in the same JSON format as before, with all
pairs included (both fixed and untouched ones)."""


def validate_qa_pairs(result: PipelineResult, all_question_numbers: list) -> list:
    """
    Runs the FINAL SELF-CHECK rules from the mapper prompt programmatically.
    Returns a list of human-readable violation strings (empty = clean).
    """
    violations = []

    # 1. overlapping answer ranges
    answered = [p for p in result.qa_pairs if p.a_start_line is not None]
    answered.sort(key=lambda p: p.a_start_line)
    for i in range(len(answered) - 1):
        a, b = answered[i], answered[i + 1]
        if a.a_end_line is not None and a.a_end_line >= b.a_start_line:
            violations.append(
                f"Overlapping answer ranges: pair(q={a.q_start_line}) a_end={a.a_end_line} "
                f"overlaps pair(q={b.q_start_line}) a_start={b.a_start_line}"
            )

    # 2. duplicate question start lines (possible merge/split error)
    seen = {}
    for p in result.qa_pairs:
        seen.setdefault(p.q_start_line, []).append(p)
    for qline, plist in seen.items():
        if len(plist) > 1:
            violations.append(f"Question at line {qline} appears in {len(plist)} qa_pairs.")

    # 3. missing questions (extraction found a question the mapper never mapped)
    mapped_starts = {p.q_start_line for p in result.qa_pairs}
    for q in all_question_numbers:
        if q.get("start_line") not in mapped_starts:
            violations.append(f"Question '{q.get('number', '?')}' at line {q.get('start_line')} was never mapped.")

    return violations


def run_refinement_loop(
    client: anthropic.Anthropic,
    numbered_lines: dict,
    result: PipelineResult,
    all_question_numbers: list,
) -> PipelineResult:
    for pass_num in range(1, MAX_REFINEMENT_PASSES + 1):
        violations = validate_qa_pairs(result, all_question_numbers)
        if not violations:
            log.info(f"Refinement pass {pass_num}: clean, no violations.")
            break

        log.info(f"Refinement pass {pass_num}: {len(violations)} violation(s) found, re-prompting.")
        current_payload = {
            "qa_pairs": [
                {
                    "q_start_line": p.q_start_line,
                    "q_end_line": p.q_end_line,
                    "a_start_line": p.a_start_line,
                    "a_end_line": p.a_end_line,
                    "continues": p.continues,
                }
                for p in result.qa_pairs
            ]
        }
        user_msg = (
            "VIOLATIONS FOUND:\n" + "\n".join(f"- {v}" for v in violations) +
            "\n\nCURRENT qa_pairs:\n" + json.dumps(current_payload, indent=2)
        )

        resp = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=4000,
            system=REFINEMENT_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_msg}],
        )
        parsed = _safe_json_parse(resp.content[0].text)
        if not parsed or "qa_pairs" not in parsed:
            result.warnings.append(f"Refinement pass {pass_num}: model returned unparseable output, keeping prior state.")
            break

        new_pairs = []
        for p in parsed["qa_pairs"]:
            q_text = _slice_lines(numbered_lines, p.get("q_start_line"), p.get("q_end_line"))
            a_text = _slice_lines(numbered_lines, p.get("a_start_line"), p.get("a_end_line"))
            new_pairs.append(QAPair(
                q_start_line=p.get("q_start_line"),
                q_end_line=p.get("q_end_line"),
                a_start_line=p.get("a_start_line"),
                a_end_line=p.get("a_end_line"),
                continues=p.get("continues", False),
                question_text=q_text,
                answer_text=a_text,
                source="llm",
            ))
        result.qa_pairs = new_pairs
    else:
        remaining = validate_qa_pairs(result, all_question_numbers)
        if remaining:
            result.warnings.append(f"{len(remaining)} violation(s) remained after {MAX_REFINEMENT_PASSES} refinement passes.")

    return result


# ---------------------------------------------------------------------------
# Stage 6: Rescue passes for unmatched questions
# ---------------------------------------------------------------------------

def rescue_unmatched_questions(
    all_question_numbers: list,
    numbered_lines: dict,
    result: PipelineResult,
) -> PipelineResult:
    """
    _rescue_unmatched_questions equivalent: for any question the mapper never
    produced a qa_pair for at all, bound its answer between this question's
    start line and the next known question's start line (bidirectional
    bounding against neighboring mapped/extracted questions), then slice raw
    text directly — no LLM involved in this fallback.
    """
    mapped_starts = {p.q_start_line for p in result.qa_pairs}
    all_starts_sorted = sorted(q["start_line"] for q in all_question_numbers if q.get("start_line") is not None)

    for q in all_question_numbers:
        qstart = q.get("start_line")
        if qstart is None or qstart in mapped_starts:
            continue

        idx = all_starts_sorted.index(qstart)
        next_start = all_starts_sorted[idx + 1] if idx + 1 < len(all_starts_sorted) else max(numbered_lines.keys()) + 1
        a_start = qstart + 1
        a_end = next_start - 1

        if a_end < a_start:
            a_start, a_end = None, None

        result.qa_pairs.append(QAPair(
            q_start_line=qstart,
            q_end_line=qstart,
            a_start_line=a_start,
            a_end_line=a_end,
            continues=False,
            question_text=q.get("text", ""),
            answer_text=_slice_lines(numbered_lines, a_start, a_end),
            source="rescue",
        ))
        result.warnings.append(f"Rescued unmatched question at line {qstart} via bidirectional bounding.")

    result.qa_pairs.sort(key=lambda p: p.q_start_line)
    return result


def final_guarantee_pass(all_question_numbers: list, result: PipelineResult) -> PipelineResult:
    """
    _final_guarantee_pass_for_unmatched equivalent: absolute last resort — if
    ANY extracted question still has no qa_pair after rescue, add a null-answer
    placeholder so downstream code (DOCX export etc.) never has to special-case
    a missing question.
    """
    mapped_starts = {p.q_start_line for p in result.qa_pairs}
    for q in all_question_numbers:
        qstart = q.get("start_line")
        if qstart is not None and qstart not in mapped_starts:
            result.qa_pairs.append(QAPair(
                q_start_line=qstart,
                q_end_line=qstart,
                a_start_line=None,
                a_end_line=None,
                question_text=q.get("text", ""),
                answer_text="",
                source="final_guarantee",
            ))
            result.warnings.append(f"Final guarantee pass: question at line {qstart} has no answer.")
    result.qa_pairs.sort(key=lambda p: p.q_start_line)
    return result


# ---------------------------------------------------------------------------
# Junk stripping
# ---------------------------------------------------------------------------

_SECTION_JUNK_PATTERNS = [
    r"^\s*[-=_*]{5,}\s*$",                  # decorative dividers
    r"^\s*\[?page\s*\d+\]?\s*$",            # page markers
    r"^\s*section\s+[ivxlc\d]+\s*$",        # section banners
    r"^\s*end of (assignment|section)\s*$",
]
_SECTION_JUNK_RE = re.compile("|".join(_SECTION_JUNK_PATTERNS), re.IGNORECASE)


def strip_section_junk(text: str) -> str:
    """_strip_section_junk equivalent — removes decorative banner lines only, never touches real content."""
    lines = text.splitlines()
    cleaned = [ln for ln in lines if not _SECTION_JUNK_RE.match(ln.strip())]
    return "\n".join(cleaned)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_json_parse(text: str):
    text = text.strip()
    text = re.sub(r"^```(json)?", "", text).strip()
    text = re.sub(r"```$", "", text).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(0))
            except json.JSONDecodeError:
                return None
        return None


# ---------------------------------------------------------------------------
# Top-level orchestration
# ---------------------------------------------------------------------------

def run_full_pipeline(pdf_path: str) -> PipelineResult:
    if not ANTHROPIC_API_KEY:
        raise RuntimeError("ANTHROPIC_API_KEY is not set in the environment.")
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    log.info("Stage 1/6: OCR (Datalab Chandra)...")
    raw_text = run_ocr(pdf_path)
    raw_text = strip_section_junk(raw_text)

    log.info("Stage 2/6: Numbering lines...")
    numbered_lines = text_to_numbered_lines(raw_text)
    result = PipelineResult(raw_lines=numbered_lines)

    log.info("Stage 3/6: Extracting questions...")
    all_questions = extract_questions(client, numbered_lines)

    log.info("Stage 4/6: Sequential answer mapping...")
    result = map_answers_with_llm_sequential(client, numbered_lines, result)

    log.info("Stage 5/6: Self-correction / refinement loop...")
    result = run_refinement_loop(client, numbered_lines, result, all_questions)

    log.info("Stage 6/6: Rescue + final guarantee passes...")
    result = rescue_unmatched_questions(all_questions, numbered_lines, result)
    result = final_guarantee_pass(all_questions, result)

    log.info(f"Pipeline complete: {len(result.qa_pairs)} qa_pairs, "
              f"{len(result.unmatched_answers)} unmatched answers, "
              f"{len(result.warnings)} warnings.")
    return result


# ---------------------------------------------------------------------------
# Inline fallback copy of the mapper system prompt (used only if
# mapper_system_prompt.txt is missing next to this file)
# ---------------------------------------------------------------------------

_INLINE_MAPPER_SYSTEM_PROMPT = """You are a STRICT LINE-RANGE MAPPING ENGINE for OCR'd document text.
You do NOT extract, rewrite, retype, or return any answer/question text.
You ONLY return line-number ranges. Return ONLY valid JSON with keys
qa_pairs (q_start_line, q_end_line, a_start_line, a_end_line, continues) and
unmatched_answers (start_line, end_line). See project docs for full rules.
NOTE: this is a fallback stub — save your full prompt as
mapper_system_prompt.txt next to pipeline.py.
"""
